// Package examplecourse is a worked example of how to configure
// textbook-to-audiobook for a specific curriculum without touching the
// generic pipeline. It sets only the fields that diverge from the
// defaults; everything else falls through to
// pipeline.Config.WithDefaults.
//
// The lesson source material is yours to supply — point LessonRoot at a
// directory of Lesson_*/ subdirectories. Nothing curriculum-specific is
// baked into the pipeline itself; this file (and the equivalent CLI
// flags below) is the whole "skin".
//
// Run with flags — the common case, no Go required:
//
//	textbook-to-audiobook run \
//	  --source ~/path/to/my-course/Module_1 \
//	  --module-num 1 \
//	  --topic "stars and stellar evolution" \
//	  --subject "introductory astronomy" \
//	  --program "an introductory astronomy course" \
//	  --persona "an experienced astronomy lecturer" \
//	  --assessment "course final" \
//	  --search-suffix "astronomy worked example" \
//	  --cover-prompt "Tasteful painterly illustration of a night sky over an observatory, no text, no labels, no people, focal subject centered. Module {{ .inputs.module_num }}: {{ .inputs.module_topic }}."
//
// Or, for fields the CLI doesn't expose (EPUB metadata, output filename
// templates), call pipeline.Build(ExampleCourseConfig(...)) directly
// from a small Go program that bakes the voice in.
package examplecourse

import (
	"fmt"

	"github.com/gallowaysoftware/textbook-to-audiobook/internal/pipeline"
)

// ExampleCourseConfig returns a textbook-to-audiobook Config skinned for
// a fictional introductory astronomy course. moduleNum and moduleTopic
// vary per run; lessonRoot is the directory holding that module's
// Lesson_*/ source.
func ExampleCourseConfig(moduleNum int, moduleTopic, lessonRoot string) pipeline.Config {
	return pipeline.Config{
		// ---- Per-run ----
		ModuleNum:   moduleNum,
		ModuleTopic: moduleTopic,
		LessonRoot:  lessonRoot,

		// ---- Voice ----
		SubjectLabel:    "introductory astronomy",
		ProgramLabel:    "an introductory astronomy course",
		ExpertPersona:   "an experienced astronomy lecturer",
		AssessmentLabel: "course final",

		// ---- Cover art ----
		// Templated on the same module_num + module_topic the generic
		// default uses, so the cover seed stays stable across reruns.
		CoverPrompt: "Tasteful painterly illustration of a night sky over an observatory, warm lamplight, soft focus, no text, no labels, no people, focal subject centered. Module {{ .inputs.module_num }}: {{ .inputs.module_topic }}.",

		// ---- Search enrichment ----
		SearchSuffix: "astronomy worked example",

		// ---- EPUB metadata (not exposed as CLI flags) ----
		// EPUBTitleTemplate and EPUBAuthor are literal strings, not Go
		// templates (unlike CoverPrompt, which IS templated): Pandoc's
		// --metadata title= takes the value verbatim, so a {{ ... }}
		// reference would land in the EPUB unexpanded. Build the title
		// from the already-resolved args.
		EPUBTitleTemplate: fmt.Sprintf("Astronomy Module %d — %s (Study Guide)", moduleNum, moduleTopic),
		EPUBAuthor:        "Generated by textbook-to-audiobook",

		// Output filename templates kept at defaults (module_<N>...).
	}
}
