// Package cibd is a worked example of how to configure
// textbook-to-audiobook for a specific curriculum. The CIBD distilling
// source material itself is private — copyrighted CIBD curriculum
// documents — so this file ships only the configuration that turns the
// generic pipeline into the CIBD-flavoured one. Drop your own lesson
// directory at LessonRoot and the pipeline reproduces the M3/M1
// deliverables the original module.yaml produced.
//
// Run with:
//
//	textbook-to-audiobook run \
//	  --source ~/path/to/cibd/source/Module_1 \
//	  --module-num 1 \
//	  --topic "fermentation and wort production" \
//	  --search-suffix "distilling spirits practical example" \
//	  --subject "CIBD distilling" \
//	  --program "the CIBD distilling certification course" \
//	  --persona "an expert distiller" \
//	  --assessment "CIBD certification exam" \
//	  --cover-prompt "Atmospheric oil painting of a traditional Scotch whisky distillery interior, copper pot still, sacks of malted barley, warm amber lighting, dusty motes in sunbeams, painterly brushwork, no text, no labels, no people, focal subject centered. Module {{ .inputs.module_num }}: {{ .inputs.module_topic }}."
//
// Or use the values in this file via a Go program that calls
// pipeline.Build(CIBDConfig(...)) directly — useful if you want to
// ship a `cibd-textbook` binary that bakes the CIBD voice in.
package cibd

import "github.com/gallowaysoftware/textbook-to-audiobook/internal/pipeline"

// CIBDConfig returns the textbook-to-audiobook Config that reproduces
// the original CIBD-distilling module.yaml pipeline. Only the fields
// that diverge from the generic defaults are set; everything else
// falls through to pipeline.Config.WithDefaults.
//
// `moduleNum` and `moduleTopic` are taken as arguments because they
// vary per run (Module 1: fermentation, Module 2: distillation, Module
// 3: production operations). `lessonRoot` is the directory holding the
// per-module Lesson_*/ source.
func CIBDConfig(moduleNum int, moduleTopic, lessonRoot string) pipeline.Config {
	return pipeline.Config{
		// ---- Per-run ----
		ModuleNum:   moduleNum,
		ModuleTopic: moduleTopic,
		LessonRoot:  lessonRoot,

		// ---- CIBD voice ----
		SubjectLabel:    "CIBD distilling",
		ProgramLabel:    "the CIBD distilling certification course",
		ExpertPersona:   "an expert distiller",
		AssessmentLabel: "CIBD certification exam",

		// ---- CIBD cover art ----
		// The original pipeline's whisky-distillery prompt. Templated
		// on the same module_num + module_topic the generic default
		// uses, so the seed (derived from module_num42) is stable.
		CoverPrompt: "Atmospheric oil painting of a traditional Scotch whisky distillery interior, copper pot still, sacks of malted barley, warm amber lighting, dusty motes in sunbeams, painterly brushwork, no text, no labels, no people, focal subject centered. Module {{ .inputs.module_num }}: {{ .inputs.module_topic }}.",

		// ---- CIBD search enrichment ----
		SearchSuffix: "distilling spirits practical example",

		// ---- EPUB metadata ----
		EPUBTitleTemplate: "CIBD Module {{ .inputs.module_num }} — {{ .inputs.module_topic }} (Study Guide)",
		EPUBAuthor:        "Generated by vamp + Qwen",

		// Output filename templates kept at defaults — module_<N>...
		// matches the original pipeline.
	}
}
